project:
  type: website

website:
  title: "Python Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: machine_learning.qmd
        text: Machine Learning
      - href: data_visualization.qmd
        text: Data Visualization
      - href: tidying_data.qmd
        text: Tidying Data
      - href: publications.qmd
        text: Publications


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



