project:
  type: website

website:
  title: "Python Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Data Science Projects
      - href: resume.qmd
        text: Resume
      - href: publications/publications.qmd
        text: Publications


format:
  html:
    # theme: cosmo
    # css: styles.css
    toc: true



